[package]
name = "css"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
cssparser = "0.28.1"
selectors = "0.23.0"
anyhow = "1.0.4"